name: Deploy live on pushes to master
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: zcong1993/setup-timezone@master
        with:
          timezone: "Australia/Sydney"
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Cache resized images
        uses: actions/cache@v2
        with:
          path: |
            .jekyll-cache/jpt
            _site/generated/assets/img
          key: 0
      - run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DANIEL_PLAYFAIR_CAL }}'
          channelId: live
          projectId: daniel-playfair-cal
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
